import { WORLD_ASSETS } from './assets.js';

export const WORLD_OBJECT_TYPES = {
  'grass-block': {
    id: 'grass-block',
    name: 'Grama',
    shape: 'model',
    modelUrl: WORLD_ASSETS.objects.kaykitGrass,
    blocksMovement: true,
    scale: 0.78,
    groundOffset: 0.04,
    color: '#ffffff',
  },
  'forest-rock': {
    id: 'forest-rock',
    name: 'Rocha',
    shape: 'model',
    modelUrl: WORLD_ASSETS.objects.kaykitRock,
    blocksMovement: true,
    scale: 0.26,
    groundOffset: 0.04,
  },
  'forest-bush': {
    id: 'forest-bush',
    name: 'Arbusto',
    shape: 'model',
    modelUrl: WORLD_ASSETS.objects.kaykitBush,
    blocksMovement: true,
    scale: 0.34,
    groundOffset: 0.04,
  },
  'forest-tree': {
    id: 'forest-tree',
    name: 'Arvore',
    shape: 'model',
    modelUrl: WORLD_ASSETS.objects.kaykitTree,
    blocksMovement: true,
    scale: 0.33,
    groundOffset: 0.04,
  },
  'dead-tree': {
    id: 'dead-tree',
    name: 'Arvore seca',
    shape: 'model',
    modelUrl: WORLD_ASSETS.objects.kaykitDeadTree,
    blocksMovement: true,
    scale: 0.38,
    groundOffset: 0.04,
  },
  stone: {
    id: 'stone',
    name: 'Rocha',
    shape: 'box',
    blocksMovement: true,
    size: { width: 0.82, height: 0.46, depth: 0.82 },
    color: '#737373',
  },
  stump: {
    id: 'stump',
    name: 'Toco',
    shape: 'cylinder',
    blocksMovement: true,
    radius: 0.36,
    height: 0.48,
    color: '#8b5a2b',
  },
  well: {
    id: 'well',
    name: 'Poco',
    shape: 'cylinder',
    blocksMovement: true,
    radius: 0.42,
    height: 0.32,
    color: '#64748b',
  },
  'nursery-pillar': {
    id: 'nursery-pillar',
    name: 'Pilar do Bercario',
    shape: 'cylinder',
    blocksMovement: true,
    radius: 0.25,
    height: 1.45,
    groundOffset: -0.045,
    contactShadow: { radius: 0.5, opacity: 0.34 },
    color: '#f4e4b2',
  },
  'nursery-pillar-broken': {
    id: 'nursery-pillar-broken',
    name: 'Pilar quebrado do Bercario',
    shape: 'cylinder',
    blocksMovement: true,
    radius: 0.27,
    height: 0.76,
    groundOffset: -0.04,
    contactShadow: { radius: 0.5, opacity: 0.28 },
    color: '#e7ce86',
  },
  'nursery-rubble': {
    id: 'nursery-rubble',
    name: 'Entulho dourado',
    shape: 'box',
    blocksMovement: true,
    size: { width: 0.62, height: 0.2, depth: 0.48 },
    groundOffset: -0.025,
    color: '#d8b45f',
  },
  'nursery-portal': {
    id: 'nursery-portal',
    name: 'Passagem do Bercario',
    shape: 'sprite',
    texture: WORLD_ASSETS.objects.portal,
    blocksMovement: false,
    size: { width: 1.25, height: 1.75 },
    color: '#fff7c2',
  },
  tree: {
    id: 'tree',
    name: 'Arvore',
    shape: 'model',
    modelUrl: WORLD_ASSETS.objects.kaykitTree,
    blocksMovement: true,
    scale: 0.33,
    groundOffset: 0.04,
  },
  'test-model': {
    id: 'test-model',
    name: 'Objeto 3D Teste',
    shape: 'model',
    modelUrl: './assets/models/test/unnamed.gltf',
    blocksMovement: true,
    scale: 0.8,
  },
};
