export const TERRAIN_TYPES = {
  grass: {
    id: 'grass',
    name: 'Grama',
    texture: null,
    color: '#3f7d46',
    procedural: 'mapColors',
  },
  stone: {
    id: 'stone',
    name: 'Pedra',
    texture: null,
    color: '#4b3a4e',
    procedural: 'mapColors',
  },
  chao3: {
    id: 'chao3',
    name: 'Chao 3',
    texture: null,
    color: '#733c50',
    procedural: 'mapColors',
  },
  debugBlue: {
    id: 'debugBlue',
    name: 'Azul claro',
    texture: null,
    color: '#8fd3ff',
    tileColors: ['#8fd3ff', '#8fd3ff'],
  },
  debugGrass: {
    id: 'debugGrass',
    name: 'Grama teste',
    texture: null,
    color: '#7dbf55',
    procedural: 'mapColors',
  },
  corrupted: {
    id: 'corrupted',
    name: 'Solo corrompido',
    texture: null,
    color: '#451329',
    procedural: 'mapColors',
  },
  dirt: {
    id: 'dirt',
    name: 'Terra',
    texture: null,
    color: '#7c5a38',
  },
};
