// Generated from assets/textures. Runtime URLs point at public/assets after asset sync.
export const TEXTURE_LIBRARY = [
  {
    id: 'textures-chao1-png',
    name: 'chao1.png',
    path: ['textures', 'chao1.png'],
    folder: 'textures',
    url: './assets/textures/chao1.png',
  },
  {
    id: 'textures-chao2-png',
    name: 'chao2.png',
    path: ['textures', 'chao2.png'],
    folder: 'textures',
    url: './assets/textures/chao2.png',
  },
  {
    id: 'textures-chao3-png',
    name: 'chao3.png',
    path: ['textures', 'chao3.png'],
    folder: 'textures',
    url: './assets/textures/chao3.png',
  },
  {
    id: 'textures-debug-grass-tile-png',
    name: 'debug-grass-tile.png',
    path: ['textures', 'debug-grass-tile.png'],
    folder: 'textures',
    url: './assets/textures/debug-grass-tile.png',
  },
  {
    id: 'textures-galho1-png',
    name: 'galho1.png',
    path: ['textures', 'galho1.png'],
    folder: 'textures',
    url: './assets/textures/galho1.png',
  },
  {
    id: 'textures-galho2-png',
    name: 'galho2.png',
    path: ['textures', 'galho2.png'],
    folder: 'textures',
    url: './assets/textures/galho2.png',
  },
  {
    id: 'textures-galho3-png',
    name: 'galho3.png',
    path: ['textures', 'galho3.png'],
    folder: 'textures',
    url: './assets/textures/galho3.png',
  },
  {
    id: 'textures-grama-decorativa-png',
    name: 'grama-decorativa.png',
    path: ['textures', 'grama-decorativa.png'],
    folder: 'textures',
    url: './assets/textures/grama-decorativa.png',
  },
  {
    id: 'textures-grama-decorativa2-png',
    name: 'grama-decorativa2.png',
    path: ['textures', 'grama-decorativa2.png'],
    folder: 'textures',
    url: './assets/textures/grama-decorativa2.png',
  },
  {
    id: 'textures-grama-lado-png',
    name: 'grama-lado.png',
    path: ['textures', 'grama-lado.png'],
    folder: 'textures',
    url: './assets/textures/grama-lado.png',
  },
  {
    id: 'textures-grama-lado-webp',
    name: 'grama-lado.webp',
    path: ['textures', 'grama-lado.webp'],
    folder: 'textures',
    url: './assets/textures/grama-lado.webp',
  },
  {
    id: 'textures-grama-topo-png',
    name: 'grama-topo.png',
    path: ['textures', 'grama-topo.png'],
    folder: 'textures',
    url: './assets/textures/grama-topo.png',
  },
  {
    id: 'textures-grama-topo-webp',
    name: 'grama-topo.webp',
    path: ['textures', 'grama-topo.webp'],
    folder: 'textures',
    url: './assets/textures/grama-topo.webp',
  },
  {
    id: 'textures-parede1-png',
    name: 'parede1.png',
    path: ['textures', 'parede1.png'],
    folder: 'textures',
    url: './assets/textures/parede1.png',
  },
  {
    id: 'textures-portal-png',
    name: 'portal.png',
    path: ['textures', 'portal.png'],
    folder: 'textures',
    url: './assets/textures/portal.png',
  },
];
